import json,re,time
from pathlib import Path
from genlayer_py import create_account,create_client
from genlayer_py.chains import studionet
ROOT=Path(__file__).parents[1];ENV=(ROOT.parents[3]/'accounts.env').read_text();ADDRESS='0xDA93F6cd63268E54Da3EF3B0E8036FE39765826b'
def account(slot):return create_account(account_private_key=re.search(rf'^ACCOUNT_{slot}_GENLAYER_PRIVATE_KEY\s*=\s*"?([^"\r\n]+)',ENV,re.M).group(1).strip())
def send(client,name,args):
 tx=client.write_contract(address=ADDRESS,function_name=name,args=args,value=0);print(name+'='+str(tx),flush=True)
 try:r=client.wait_for_transaction_receipt(transaction_hash=tx,wait_until='finalized',retries=180,interval=5000,full_transaction=True)
 except TypeError:r=client.wait_for_transaction_receipt(transaction_hash=tx,status='FINALIZED',retries=180,interval=5000,full_transaction=True)
 leader=(r.get('consensus_data',{}).get('leader_receipt') or [{}])[0];assert str(r.get('result_name')).upper()=='MAJORITY_AGREE' and str(leader.get('execution_result')).upper()=='SUCCESS',(name,r);return str(tx)
buyer,contractor,oversight=account(1),account(2),account(3);a=create_client(chain=studionet,account=buyer);b=create_client(chain=studionet,account=contractor);c=create_client(chain=studionet,account=oversight);record='SR-LIVE-'+str(int(time.time()));urls={'rules':'https://samiinw-scope-ratchet.pages.dev/materiality-rules.txt','award':'https://4bb4ea7b.samiinw-scope-ratchet.pages.dev/award.txt','a':'https://4fe024f2.samiinw-scope-ratchet.pages.dev/change-order-a.txt','b':'https://4fe024f2.samiinw-scope-ratchet.pages.dev/change-order-b.txt'};txs={}
txs['open']=send(a,'open_procurement',[record,contractor.address,oversight.address,urls['rules'],urls['award'],100000,1000,30]);txs['orderA']=send(b,'file_change_order',[record,urls['a']]);first=b.read_contract(address=ADDRESS,function_name='get_order',args=[record,1]);assert first['impact_bps']==600 and first['requires_retender'] is False,first;time.sleep(35);txs['finalizeA']=send(c,'finalize_order',[record]);mid=a.read_contract(address=ADDRESS,function_name='get_procurement',args=[record]);assert mid['state']=='OPEN' and mid['cumulative_bps']==600,mid;txs['orderB']=send(b,'file_change_order',[record,urls['b']]);second=b.read_contract(address=ADDRESS,function_name='get_order',args=[record,2]);assert second['impact_bps']==450 and second['projected_bps']==1050 and second['requires_retender'] is True,second;time.sleep(35);txs['finalizeB']=send(c,'finalize_order',[record]);final=a.read_contract(address=ADDRESS,function_name='get_procurement',args=[record]);assert final['state']=='RETENDER_REQUIRED',final;print(json.dumps({'recordId':record,'state':final['state'],'cumulativeBeforeStop':final['cumulative_bps'],'secondProjectedBps':second['projected_bps'],'transactions':txs},default=str),flush=True)
